services:
  portfolio:
    image: captainigl00/portfolio:latest
    labels:
      - "traefik.enable=true"

      # === Main domain ===
      - "traefik.http.routers.portfolio.rule=Host(`matheo.guilloux.ovh`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

      # === Variant www. + redirect to root ===
      - "traefik.http.routers.portfolio-www.rule=Host(`www.matheo.guilloux.ovh`)"
      - "traefik.http.routers.portfolio-www.entrypoints=websecure"
      - "traefik.http.routers.portfolio-www.tls.certresolver=myresolver"
      - "traefik.http.routers.portfolio-www.middlewares=www-redirect@docker"
      - "traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www\\.matheo\\.guilloux\\.ovh/(.*)"
      - "traefik.http.middlewares.www-redirect.redirectregex.replacement=https://matheo.guilloux.ovh/$$1"
      - "traefik.http.middlewares.www-redirect.redirectregex.permanent=true"

      # Compression: save some bytes
      - "traefik.http.middlewares.compression.compress=true"
      - "traefik.http.routers.portfolio.middlewares=compression@docker"

      # Watchtower
      - "com.centurylinklabs.watchtower.scope=app"  # same scope as your other apps

    restart: unless-stopped
    networks:
      - web            # <- same network as Traefik
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    external: true     # reuse the existing "traefik_network" network
